Update WebControl's README for new state of the art
WebControlCNC/WebControl pull request #161
Opened 2020-06-01 20:17 UTC by zaneclaes

@madgrizzle first pass an some updates to the README.

I'll do the CI update & absolute paths in a separate PR, just trying to nail workflow.

2020-06-01 20:35 UTC, emilecantin requested changes
Typo needs to be fixed, otherwise looks good!

2020-06-01 20:35 UTC, emilecantin commented on docs/index.md
> +WebControl started as a browser-based port of the original GroundControl applicaiton, but has grown to support more features:
Typo: application

2020-06-01 20:35 UTC, emilecantin commented on docs/index.md
> +WebControl can be run behind a front-proxy with TLS termination, such as nginx. You can use this in conjunction with semi-static IP to access your Maslow from anywhere with internet access. The full
Open to debate on this, but the term I've seen most often in the industry is reverse-proxy.

2020-06-01 20:53 UTC, zaneclaes commented on docs/index.md
> +WebControl can be run behind a front-proxy with TLS termination, such as nginx. You can use this in conjunction with semi-static IP to access your Maslow from anywhere with internet access. The full
A "reverse-proxy" is correct yah, because the backend (WebControl) knows the client's identity and not vice-versa. A "forward proxy" would be the inverse of a reverse proxy. But I **believe** that a "front-proxy" is actually something different than a "forward proxy." I got this impression from [Envoy's docs](https://www.envoyproxy.io/learn/front-proxy), which refer to this kind of load-balancing/edge-node behavior as a "front proxy" for a backend application.

2020-06-01 20:57 UTC, zaneclaes commented
Thanks @emilecantin ! Looks like the HackMD workflow is good enough, too. I was worried it was going to squash commits or force push or something silly, but it seems pretty natively integrated with version control concepts

2020-06-02 00:33 UTC, zaneclaes commented
@emilecantin or @madgrizzle I think I need a proper approval.

2020-06-02 04:36 UTC, emilecantin commented on docs/index.md
> +WebControl started as a browser-based port of the original GroundControl applicaiton, but has grown to support more features:
@zaneclaes You marked as resolved, but it's still wrong in the diff. Did you push the change?

2020-06-02 13:15 UTC, zaneclaes commented on docs/index.md
> +WebControl started as a browser-based port of the original GroundControl applicaiton, but has grown to support more features:
Hah, I spoke too soon about HackMD doing the commit properly. I managed to push a commit without actually adding the changes, which made HackMD think it had pushed all changes when it had not done so 😥 

Working SHA: https://github.com/WebControlCNC/WebControl/pull/161/commits/abb8dae2e7c781d19bf92f63ff675ec68f82e342

2020-06-02 13:22 UTC, emilecantin approved these changes

2020-06-02 13:58 UTC, merged

2020-06-02 14:57 UTC, emilecantin commented
@zaneclaes Don't we want to update the actual README with these changes as well? So people coming into the repo see the same thing.

2020-06-02 15:02 UTC, zaneclaes commented
@emilecantin yes — but the way HackMD works, it's basically a checkout of the git repo. However, only this one file has been checked out, and apparently I need the owner (@madgrizzle) to check out the rest of the files into HackMD before I can actually use it to edit them _sigh_. It is a nice tool though, makes editing easy.

2020-06-02 15:17 UTC, emilecantin commented
I guess you could just copy the whole thing manually, without using HackMD? I believe README.md and docs/index.md are supposed to be the same thing anyway.

2020-06-02 15:39 UTC, zaneclaes commented
Well, the whole point of the exercise was to find a tool where we could centralize the docs for Maslow, even though they're split between repos...

Unless we're in a hurry to get these updated? I mean, I'm happy to just check out the repo and use Sublime like normal 🙃

2020-06-02 15:40 UTC, emilecantin commented
The tool is probably alright for the docs in general; README / index.md just has a special status.

2020-06-02 19:07 UTC, madgrizzle commented
I pulled in another file, the index from the GettingStarted subdirectory.  I'm worried about how everything is being pulled in and organized.  It appears to just use tags, rather than an hierarchical structure.

2020-06-02 19:11 UTC, madgrizzle commented
Is there a better OVERALL system we can use (something other than github pages)?  It would be nice to have the ability to readily edit the documentation and have it available for off-line help... however that might happen.

2020-06-02 19:29 UTC, zaneclaes commented
@madgrizzle there are a lot of wikis software flavors out there to choose from. Unfortunately, most of the good software would cost a hosting fee. If we could find something we wanted to self host, I'd offer my AWS cluster an experience managing websites. Do we know who actually owns `MaslowCNC.com`? Is that Bar as well?

2020-06-02 19:44 UTC, madgrizzle commented
I'm pretty sure bar owns it.

2020-06-02 21:58 UTC, Orob-Maslow commented
The GitHub wiki works and is editable, why not just stay with that dead
simple setup?  Put a link in webcontrol and call it good.  Is the goal to
have a synced copy of online and distributed documentation with the
software?  If so I see the issue, if not, why all the md file concerns,
editors, tags, etc.  Are the docs for documenting the code for the next
developer or a user guide to get the new guy going?

On Tue, Jun 2, 2020, 2:45 PM madgrizzle <notifications@github.com> wrote:

> I'm pretty sure bar owns it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WebControlCNC/WebControl/pull/161#issuecomment-637767079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOGADD3AI56555KYFSLB3Z3RUVJETANCNFSM4NQDSVZA>
> .
>

2020-06-02 22:02 UTC, madgrizzle commented
The files were setup so the same file could be used for GitHub pages as well as offline help embedded into webcontrol.  All the formatting and things you see in the file are part of theme used for GitHub pages (it uses justthedocs) it was a clean solution that didn't require me to duplicate things.

2020-06-03 15:41 UTC, zaneclaes commented
Okay, he and I are chatting via DMs on the forums. I'm asking him what his thoughts are on the matter.